services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - db
    volumes:
      - .:/work

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/work
    depends_on:
      - php
    ports:
      - 80:80

  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: medical-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  db-testing:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: medical-db-testing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 33306:3306
    volumes:
      - db_testing_data:/var/lib/mysql

volumes:
  db_data:
  db_testing_data:
